module.exports = {
  apps: {
    name: "server",
    script: "npm",
    args: "run pm2",
    instances: "max",
    exec_mode: "cluster",
    env_production: {
      HOST: "0.0.0.0",
      PORT: 1115,
      NODE_ENV: "production",
      APP_NAME: "smartschool",
      APP_URL: "http://${HOST}:${PORT}",
      CACHE_VIEWS: false,
      APP_KEY: "JD93YQ9BEY5vN8sERTZ4unRWzyqytYWO",
      DB_CONNECTION: "mysql",
      DB_HOST: "localhost",
      DB_PORT: 3306,
      DB_USER: "goent",
      DB_PASSWORD: "server1goent26sukses",
      DB_DATABASE: "ss",
      HASH_DRIVER: "bcrypt",
      TZ: "Asia/Jakarta",
      GCP_API_KEYS: "AIzaSyAeIMzWUV3w1A39AZcV8NxICLlUh5SJLj4",
      GOOGLE_CLOUD_PROJECT_ID: "smart-school-300211",
      GOOGLE_CLOUD_KEY_FILE: "smart-school-300211-b581563b21c0.json",
      GOOGLE_CLOUD_STORAGE_BUCKET: "smartschool",
      GOOGLE_CLOUD_STORAGE_PATH_PREFIX: "",
      SMTP_host: "smtp.zoho.com",
      MAIL_USERNAME: "no-reply@smarteschool.id",
      MAIL_PASSWORD: "Ri2DddrGFuyU",
    },
  },
  deploy: {
    production: {
      user: "root",
      host: ["149.28.144.177", "45.32.120.76", "128.199.64.198"],
      key: "/d/work/coba/ci_cd/id_rsa",
      ref: "origin/master",
      repo: "git@github.com:rochim26/server-smartschool.git",
      path: "/root/adonis_cd",
      "post-deploy": "npm i",
    },
  },
};
